
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";


export const LIVE_VERIFY_REQUEST = "LIVE_VERIFY_REQUEST";
export const LIVE_VERIFY_SUCCESS = "LIVE_VERIFY_SUCCESS";
export const LIVE_VERIFY_FAILURE = "LIVE_VERIFY_FAILURE";


export const LOGOUT = "LOGOUT";